name: Build Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build for Linux
      run: GOOS=linux GOARCH=amd64 go build -o ${{ github.repository_owner }}-${{ github.repository_name }}-linux-amd64

    - name: Build for Windows
      run: GOOS=windows GOARCH=amd64 go build -o ${{ github.repository_owner }}-${{ github.repository_name }}-windows-amd64.exe

    - name: Build for macOS
      run: GOOS=darwin GOARCH=amd64 go build -o ${{ github.repository_owner }}-${{ github.repository_name }}-darwin-amd64
